version: "3.8"
services:
  postgres:
    image: postgres
    container_name: infyra
    environment:
      POSTGRES_USER: infyra
      POSTGRES_PASSWORD: root
      POSTGRES_DB: infyra
    ports:
      - "5433:5432"
    volumes:
      - ./tmp/infyra:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: infyra-redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
    command: ["redis-server", "--appendonly", "yes"]