/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as protectedLayoutRouteImport } from './pages/(protected)/_layout'
import { Route as AuthLayoutRouteImport } from './pages/auth/_layout'
import { Route as protectedIndexRouteImport } from './pages/(protected)/index'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as AuthRegisterRouteImport } from './pages/auth/register'
import { Route as protectedConnectorsIndexRouteImport } from './pages/(protected)/connectors/index'
import { Route as protectedProjectsIndexRouteImport } from './pages/(protected)/projects/index'
import { Route as protectedProjectsProjectSlugRouteImport } from './pages/(protected)/projects/$projectSlug'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const protectedConnectorsIndexRoute =
  protectedConnectorsIndexRouteImport.update({
    id: '/connectors/',
    path: '/connectors/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedProjectsIndexRoute = protectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedProjectsProjectSlugRoute =
  protectedProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof protectedIndexRoute
  '/projects/$projectSlug': typeof protectedProjectsProjectSlugRoute
  '/connectors/': typeof protectedConnectorsIndexRoute
  '/projects/': typeof protectedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof protectedIndexRoute
  '/projects/$projectSlug': typeof protectedProjectsProjectSlugRoute
  '/connectors': typeof protectedConnectorsIndexRoute
  '/projects': typeof protectedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/projects/$projectSlug': typeof protectedProjectsProjectSlugRoute
  '/(protected)/connectors/': typeof protectedConnectorsIndexRoute
  '/(protected)/projects/': typeof protectedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/projects/$projectSlug'
    | '/connectors/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/projects/$projectSlug'
    | '/connectors'
    | '/projects'
  id:
    | '__root__'
    | '/(protected)'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/(protected)/'
    | '/(protected)/projects/$projectSlug'
    | '/(protected)/connectors/'
    | '/(protected)/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(protected)/connectors/': {
      id: '/(protected)/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof protectedConnectorsIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/projects/': {
      id: '/(protected)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof protectedProjectsIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/projects/$projectSlug': {
      id: '/(protected)/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof protectedProjectsProjectSlugRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedIndexRoute: typeof protectedIndexRoute
  protectedProjectsProjectSlugRoute: typeof protectedProjectsProjectSlugRoute
  protectedConnectorsIndexRoute: typeof protectedConnectorsIndexRoute
  protectedProjectsIndexRoute: typeof protectedProjectsIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedIndexRoute: protectedIndexRoute,
  protectedProjectsProjectSlugRoute: protectedProjectsProjectSlugRoute,
  protectedConnectorsIndexRoute: protectedConnectorsIndexRoute,
  protectedProjectsIndexRoute: protectedProjectsIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
